apiVersion: v1
kind: Service
metadata:
  name: front-gateway
  labels:
    name: front-gateway
spec:
  selector:
    name: front-gateway
  type: NodePort
  ports:
   - port: 8000
     name: http
     targetPort: 8000
     protocol: TCP
     nodePort: 32500
