apiVersion: v1
kind: Service
metadata:
  name: munich
  labels:
    name: munich
spec:
  selector:
    name: munich
  ports:
   - port: 8000
     targetPort: 8000
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: munich
  labels:
    name: munich
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: munich
    spec:
      containers:
        - name: munich
          image: zkan/munich:latest
