apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nyc
  labels:
    name: nyc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nyc
    spec:
      containers:
        - name: nyc
          image: zkan/nyc:latest
