apiVersion: v1
kind: Service
metadata:
  name: tokyo
  labels:
    name: tokyo
spec:
  selector:
    name: tokyo
  ports:
   - port: 3000
     targetPort: 3000
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tokyo
  labels:
    name: tokyo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: tokyo
    spec:
      containers:
        - name: tokyo
          image: zkan/tokyo:latest
